AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS cluster resources'

Parameters:
  Environment:
    Type: String
  EksVersion:
    Type: String
  EksClusterMinSize:
    Type: String
  EksClusterDesiredSize:
    Type: String
  EksClusterMaxSize:
    Type: String
  EksNodeInstanceType:
    Type: String
  EksRoleArn:
    Type: String
  NodeInstanceRole:
    Type: String
  PublicSubnet01:
    Type: String
  PublicSubnet02:
    Type: String
  PrivateSubnet01:
    Type: String
  PrivateSubnet02:
    Type: String
  ControlPlaneSecurityGroup:
    Type: String

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Join [ "-", [!Ref Environment, NodeInstanceRole] ]
      Version: !Ref EksVersion
      RoleArn: !Ref EksRoleArn
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Ref ControlPlaneSecurityGroup
        SubnetIds:
        - !Ref PublicSubnet01
        - !Ref PublicSubnet02
        - !Ref PrivateSubnet01
        - !Ref PrivateSubnet02

  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref EKSCluster
      NodeRole: !Ref NodeInstanceRole
      ScalingConfig:
        MinSize: !Ref EksClusterMinSize
        DesiredSize: !Ref EksClusterDesiredSize
        MaxSize: !Ref EksClusterMaxSize
      Subnets:
        - !Ref PrivateSubnet01
        - !Ref PrivateSubnet02

Outputs:
  EksClusterName: 
    Value: !Ref EKSCluster