AWSTemplateFormatVersion: '2010-09-09'
Description: 'Load Balancer resources'

Parameters:
  Environment:
    Type: String
  EksClusterName:
    Type: String
  VpcId:
    Type: String
  PublicSubnet01:
    Type: String
  PublicSubnet02:
    Type: String
  AlbScheme:
    Type: String
  AlbGroupName:
    Type: String
  
Resources:

  # Used by the K8s cluster as Ingress
  IngressAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: !Join [ "-", [!Ref Environment, alb] ]
      Type: application
      Scheme: !Ref AlbScheme
      Subnets: 
        - !Ref PublicSubnet01
        - !Ref PublicSubnet02
      Tags:
        - Key: ingress.k8s.aws/resource
          Value: LoadBalancer
        - Key: elbv2.k8s.aws/cluster
          Value: !Ref EksClusterName
        - Key: ingress.k8s.aws/stack
          Value: !Ref AlbGroupName

Outputs:
  IngressAlbArn:
    Value: !Ref IngressAlb